DoAnCNTT_HH/Areas/Member/Controllers/LoginMemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAnCNTT_HH.Areas.Member.Controllers
{
    public class LoginMemberController : Controller
    {
        // GET: Member/LoginMember
        public ActionResult DangNhap()
        {
            return View();
        }
        public ActionResult DangKi()
        {
            return View();
        }
    }
}

DoAnCNTT_HH/Views/Shared/DmCsharp.cshtml
@{
    Layout = null;
}
@model List<Model.EF.BaiHoc>
@*@if(Model.DanhMucKienThucID)*@


@*<ul class="list-group">
        <li class="list-group-item active">Bài học Csharp</li>
        @foreach (var item in Model)
        {
            var url = "/learn/" + item.TieuDeSeo + "-" + item.BaiHocID;

            <li class="list-group-item disabled">
                <a href="@url">@item.Ten.ToString(): @item.TieuDe.ToString()</a>
            </li>


        }


    </ul>*@



<div>
    <h5>Bài học Csharp</h5>
    @foreach (var item in Model)
    {
        var url = "/learn/" + item.TieuDeSeo + "-" + item.BaiHocID;

        <a href="@url">@item.Ten.ToString(): @item.TieuDe.ToString()</a>
        <br>
    }
    @*<ul class="list-group">

        @foreach (var item in Model)
        {
            var url = "/learn/" + item.TieuDeSeo + "-" + item.BaiHocID;

            <li class="list-group-item disabled">
                <a href="@url">@item.Ten.ToString(): @item.TieuDe.ToString()</a>
            </li>


        }
        @foreach (var item in Model)
        {
            var url = "/learn/" + item.TieuDeSeo + "-" + item.BaiHocID;

            <li class="list-group-item disabled">
                <a href="@url">@item.Ten.ToString(): @item.TieuDe.ToString()</a>
            </li>


        }

    </ul>*@


</div>

DoAnCNTT_HH/Views/Shared/DmJava.cshtml
@{
    Layout = null;
}
@model List<Model.EF.BaiHoc>

<div>

    @*<ul class="list-group">
        <li class="list-group-item active">Bài học Java</li>
        @foreach (var item in Model)
        {
            var url = "/learn/" + item.TieuDeSeo + "-" + item.BaiHocID;
            <li class="list-group-item disabled">
                <a href="@url">@item.Ten.ToString(): @item.TieuDe.ToString()</a>
            </li>

        }


    </ul>*@


    <div >
        <h5>Bài học Java</h5>
        @foreach (var item in Model)
        {
            var url = "/learn/" + item.TieuDeSeo + "-" + item.BaiHocID;

            <a href="@url">@item.Ten.ToString(): @item.TieuDe.ToString()</a>
            <br>


        }

    </div>
</div>

DoAnCNTT_HH/Views/Shared/DmPython.cshtml
@{
    Layout = null;
}
@model List<Model.EF.BaiHoc>

<div>

    @*<ul class="list-group">
            <li class="list-group-item active">Bài học Python</li>
            @foreach (var item in Model)
            {
                var url = "/learn/" + item.TieuDeSeo + "-" + item.BaiHocID;
                <li class="list-group-item disabled">
                    <a href="@url">@item.Ten.ToString(): @item.TieuDe.ToString()</a>
                </li>

            }


        </ul>*@


    <h5>Bài học Python</h5>
    @foreach (var item in Model)
    {
        var url = "/learn/" + item.TieuDeSeo + "-" + item.BaiHocID;

        <a href="@url">@item.Ten.ToString(): @item.TieuDe.ToString()</a>
        <br>


    }

</div>

DoAnCNTT_HH/Views/Shared/Footer.cshtml
@{
    Layout = null;
}

@*<footer>
    <div class="footer-bottom">
        <div class="container-fluid">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6 ">
                        <div class="copyright-text">
                            <p>CopyRight ©@DateTime.Now.Year ITBlues chia sẻ kiến thức</p>
                        </div>
                    </div> <!-- End Col -->
                    <div class="col-sm-6  ">
                        <div class="copyright-text pull-right">
                            <p> @Html.ActionLink("Trang chủ", "Index", "Home") | <a href="#">Chính sách</a> |<a href="#">Terms & Conditions</a> | <a href="#">Refund Policy</a> </p>
                        </div>

                    </div> <!-- End Col -->
                </div>
            </div>
        </div>
    </div>
</footer>*@





















@*<footer class="text-light">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-lg-4 col-xl-3">
                    <h5>About</h5>
                    <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                    <p class="mb-0">
                        Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression.
                    </p>
                </div>
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto">
                    <h5>Informations</h5>
                    <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                    <ul class="list-unstyled">
                        <li><a href="">Link 1</a></li>
                        <li><a href="">Link 2</a></li>
                        <li><a href="">Link 3</a></li>
                        <li><a href="">Link 4</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto">
                    <h5>Others links</h5>
                    <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                    <ul class="list-unstyled">
                        <li><a href="">Link 1</a></li>
                        <li><a href="">Link 2</a></li>
                        <li><a href="">Link 3</a></li>
                        <li><a href="">Link 4</a></li>
                    </ul>
                </div>
                <div class="col-md-4 col-lg-3 col-xl-3">
                    <h5>Contact</h5>
                    <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                    <ul class="list-unstyled">
                        <li><i class="fa fa-home mr-2"></i> My company</li>
                        <li><i class="fa fa-envelope mr-2"></i> email@example.com</li>
                        <li><i class="fa fa-phone mr-2"></i> + 33 12 14 15 16</li>
                        <li><i class="fa fa-print mr-2"></i> + 33 12 14 15 16</li>
                    </ul>
                </div>
                <div class="col-12 copyright mt-3">
                    <p class="float-left">
                        <a href="#">Back to top</a>
                    </p>
                    <p class="text-right text-muted">created with <i class="fa fa-heart"></i> by <a href="https://t-php.fr/43-theme-ecommerce-bootstrap-4.html"><i>t-php</i></a> | <span>v. 1.0</span></p>
                </div>
            </div>
        </div>
    </footer>*@

DoAnCNTT_HH/Views/Shared/TopMenu.cshtml
@{
    Layout = null;
}
@model List<Model.EF.DanhMucKienThuc>

<div>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark fixed-top">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            @Html.ActionLink("IT Bluesky", "Next", "Home", new { @class = "navbar-brand" })
            <!-- Navbar links -->

            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        @Html.ActionLink("Trang chủ", "Next", "Home", new { @class = "nav-link" })
                    </li>
                    <li class="nav-item active">
                        @Html.ActionLink("Tin tức", "Next", "Home", new { @class = "nav-link" })

                    </li>

                    <!-- Dropdown -->
                    <li class="nav-item dropdown active">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            Kiến thức
                        </a>
                        <div class="dropdown-menu">
                            @foreach (var item in Model)
                            {
                                //nhược điểm không tạo được đường link thân thiện
                                <a class="dropdown-item" href="/KienThuc/@item.Link">@item.Ten.ToString()</a>
                            }

                        </div>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Tài liệu</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Diễn đàn</a>
                    </li>
                    <li class="nav-item active">
                        @Html.ActionLink("Giới thiệu", "About", "Home", new { @class = "nav-link" })

                    </li>



                </ul>
                <form class="form-inline my-2 my-lg-0" action="tim-kiem" method="post">
                    <input class="form-control mr-sm-2" type="text" id="txtKeyword" name="searching" style="background-color :seashell" placeholder="Tìm kiếm">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Tìm kiếm</button>
                </form>

                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item">

                        @Html.ActionLink("Đăng nhập", "DangNhap", "LoginMember", new { area = "Member" }, new { @class = "btn btn-dark" })

                    </li>
                </ul>

            </div>

        </div>
    </nav>



</div>

DoAnCNTT_HH/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Website chia sẻ kiến thức</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    @*css footer*@
    <link rel="stylesheet" href="~/Assets/Client/footer.css" />
    <link rel="stylesheet" href="~/Assets/Admin/css/MyTopMenu.css" />
    <link rel="stylesheet" href="~/Assets/Client/css/Tintuc.css">




</head>
<body style="background-color:#f1f1f1">



    @*Topmenu*@
    @{ Html.RenderAction("TopMenu", "Home");}

    <br>
    <br>
    <div class="container-fluid">


        @*<div class="container-fluid">*@
        @RenderBody()
        @*</div>*@
    </div>

    @*Footer*@
    @RenderPage("~/Views/Shared/Footer.cshtml")


    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="~/Assets/Client/js/TimKiem.js"></script>

</body>
</html>

DoAnCNTT_HH/Views/Shared/_Layout_KienThuc.cshtml
@{
    ViewBag.Title = "_Layout_KienThuc";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br>
<div @*class="container-fluid"*@>
    <div class="row">
        <div class="col-lg-3" >

            <div style="overflow :auto;height:550px;background-color:#ffffff">
                @RenderSection("kienthuc", required: false)
                @RenderSection("temp", required: false)
            </div>
        </div>
        <div class="col-lg-9" style=" background-color:#ffffff">
            @RenderBody()
        </div>
    </div>
</div>